### ISSUE TITLE
compile failed with gcc8.2.1(20181127)

### ISSUE THREAD

**Issue by cmsxbc** [xuanyan0x7c7/insertionfinder#1]
g++ -std=gnu++17 -DHAVE_CONFIG_H -I. -I..  -I../include   -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cpp                                                                                      
mv -f .deps/main.Tpo .deps/main.Po
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -std=gnu++17  -g -O2   -o insertionfinder main.o cli/libcli.la cli/univalue/libunivalue.la finder/libfinder.la case/libcase.la cube/libcube.la algorithm/libalgorithm.la -pthread -lboost_system -lboost_filesystem -lboost_program_options
libtool: link: g++ -std=gnu++17 -g -O2 -o insertionfinder main.o -pthread  cli/.libs/libcli.a cli/univalue/.libs/libunivalue.a finder/.libs/libfinder.a case/.libs/libcase.a cube/.libs/libcube.a algorithm/.libs/libalgorithm.a -lboost_system -lboost_filesystem -lboost_program_options -pthread
/usr/bin/ld: cli/.libs/libcli.a(search.o): in function `InsertionFinder::CLI::find_insertions(boost::program_options::variables_map const&)':                                                                     
/usr/include/c++/8.2.1/bits/fs_path.h:183: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'                                                                                              
/usr/bin/ld: cli/.libs/libcli.a(search.o): in function `InsertionFinder::CLI::find_insertions(boost::program_options::variables_map const&)':                                                                     
/usr/include/c++/8.2.1/bits/fs_dir.h:356: undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: cli/.libs/libcli.a(search.o): in function `InsertionFinder::CLI::find_insertions(boost::program_options::variables_map const&)':                                                                     
/home/lane/Github/insertionfinder/src/cli/search.cpp:230: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'                                                                
/usr/bin/ld: cli/.libs/libcli.a(search.o): in function `InsertionFinder::CLI::find_insertions(boost::program_options::variables_map const&)':                                                                     
/usr/include/c++/8.2.1/bits/fs_ops.h:213: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'                                                                                 
/usr/bin/ld: cli/.libs/libcli.a(search.o): in function `InsertionFinder::CLI::find_insertions(boost::program_options::variables_map const&)':                                                                     
/home/lane/Github/insertionfinder/src/cli/search.cpp:230: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'                                                                     
/usr/bin/ld: cli/.libs/libcli.a(search.o): in function `InsertionFinder::CLI::find_insertions(boost::program_options::variables_map const&)':                                                                     
/usr/include/c++/8.2.1/bits/fs_path.h:183: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'                                                                                              
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:379: undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'                                                                       
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:256: undefined reference to `std::filesystem::__cxx11::path::has_filename() const'                                                                             
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:259: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'                                                                                 
/usr/bin/ld: cli/.libs/libcli.a(search.o): in function `InsertionFinder::CLI::find_insertions(boost::program_options::variables_map const&)':                                                                     
/usr/include/c++/8.2.1/bits/fs_dir.h:356: undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: cli/.libs/libcli.a(search.o): in function `InsertionFinder::CLI::find_insertions(boost::program_options::variables_map const&)':                                                                     
/home/lane/Github/insertionfinder/src/cli/search.cpp:241: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'                                                                
/usr/bin/ld: cli/.libs/libcli.a(search.o): in function `InsertionFinder::CLI::find_insertions(boost::program_options::variables_map const&)':                                                                     
/usr/include/c++/8.2.1/bits/fs_ops.h:213: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'                                                                                 
/usr/bin/ld: cli/.libs/libcli.a(search.o): in function `InsertionFinder::CLI::find_insertions(boost::program_options::variables_map const&)':                                                                     
/home/lane/Github/insertionfinder/src/cli/search.cpp:241: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'                                                                     
/usr/bin/ld: cli/.libs/libcli.a(search.o): in function `InsertionFinder::CLI::find_insertions(boost::program_options::variables_map const&)':                                                                     
/usr/include/c++/8.2.1/bits/fs_path.h:176: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'                                                                                              
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:379: undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'                                                                       
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:256: undefined reference to `std::filesystem::__cxx11::path::has_filename() const'                                                                             
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:259: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'                                                                                 
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:183: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'                                                                                 
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:1054: undefined reference to `std::filesystem::__cxx11::path::_M_find_extension() const'                                                                       
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:544: undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'                                             
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:183: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'                                                                                 
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:1054: undefined reference to `std::filesystem::__cxx11::path::_M_find_extension() const'                                                                       
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:544: undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'                                             
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:176: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'                                                                                 
/usr/bin/ld: /usr/include/c++/8.2.1/bits/fs_path.h:176: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'                                                                                 
/usr/bin/ld: cli/.libs/libcli.a(search.o):(.data.rel.local.DW.ref._ZTINSt10filesystem7__cxx1116filesystem_errorE[DW.ref._ZTINSt10filesystem7__cxx1116filesystem_errorE]+0x0): undefined reference to `typeinfo for
std::filesystem::__cxx11::filesystem_error'
collect2: error: ld returned 1 exit status

**Comment by xuanyan0x7c7** [comment]
Try `./configure LIBS=-lstdc++fs` first, I'll fix it

**Comment by cmsxbc** [comment]
> Try `./configure LIBS=-lstdc++fs` first, I'll fix it

It works!
