### ISSUE TITLE
Support for caret NISS notation

### ISSUE THREAD

**Issue by lgarron** [xuanyan0x7c7/insertionfinder#4]
Ahoy! In order to prepare for some cubing ecosystem changes, I'm trying to promote compatibility with caret NISS notation: https://www.speedsolving.com/threads/caret-niss-notation-b-l-u-f2.88529/

Some FMC folks use parentheses, but unfortunately this is incompatible with various cubing software. Caret NISS notation solves this by using a `^` (caret symbol) before any "inverse scramble" moves in parentheses:

```
^(B L' U F2) // Nice start on inverse scramble
D' B' U B2 R2 // Nice continuation
^(R B R' U R' U2 R B) //F2L
^(U2 R' U2 R' D' L F2 L' D R2) // LL
// From https://fmcsolves.cubing.net/fmc_tutorial_ENG.pdf
```

I'd like to offer a change to Insertion Finder to accept caret NISS notation as input, which would allow such solutions to be e.g. pasted to and from Twizzle, and shared on speedsolving.com with an animated player. It wouldn't break any existing functionality — it would just allow a caret in front of `(`.

This seems to be fairly straightforward in the JS code, but I can only find the minified code. If compatibility with caret NISS notation is amenable, Is there a frontend codebase I could contribute to?

**Comment by lgarron** [comment]
@xuanyan0x7c7 Any chance I could ask for your reasoning?

Without an alternative to regular parentheses, FMC notation will become steadily incompatible with other notation. I'd like to ensure that algs/solutions can be freely pasted between tools where possible, since that lowers the cognitive overhead for cubers that are in the middle of exploring solutions.

Caret NISS notation has been supported by Twizzle Editor for a while, and is supported by https://fmcworkshop.com/ as well.

**Comment by xuanyan0x7c7** [comment]
> @xuanyan0x7c7 Any chance I could ask for your reasoning?
> 
> Without an alternative to regular parentheses, FMC notation will become steadily incompatible with other notation. I'd like to ensure that algs/solutions can be freely pasted between tools where possible, since that lowers the cognitive overhead for cubers that are in the middle of exploring solutions.
> 
> Caret NISS notation has been supported by Twizzle Editor for a while, and is supported by https://fmcworkshop.com/ as well.

This is the core repo of insertionfinder, it only accept face moves as scrambles and skeletons, users should format algorithms before passing to the program.

**Comment by Baiqiang** [comment]
> @xuanyan0x7c7 Any chance I could ask for your reasoning?
> 
> Without an alternative to regular parentheses, FMC notation will become steadily incompatible with other notation. I'd like to ensure that algs/solutions can be freely pasted between tools where possible, since that lowers the cognitive overhead for cubers that are in the middle of exploring solutions.
> 
> Caret NISS notation has been supported by Twizzle Editor for a while, and is supported by https://fmcworkshop.com/ as well.

@lgarron If you are looking for the web tool insertion finder, it has been supported. Here's an example: https://333.fm/if/2b19f271932909005042bf4d3df6dc2c

**Comment by lgarron** [comment]
> @lgarron If you are looking for the web tool insertion finder, it has been supported. Here's an example: https://333.fm/if/2b19f271932909005042bf4d3df6dc2c

oooooh, I'm so glad to see it! 🤩
